## Harshal Tak
## 32567

### Implement a system to detect different types of toxicity like threats, obscenity, insults, and 
### identity-based hate from comments

In [23]:
import pandas as pd
import numpy as np
from nltk import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [2]:
train_df = pd.read_csv('train.csv')
train_df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [3]:
test_df = pd.read_csv('test.csv')
test_df.head()

id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [4]:
sample = pd.read_csv('sample_submission.csv')
sample.head()

id  toxic  severe_toxic  obscene  threat  insult  \
0  00001cee341fdb12    0.5           0.5      0.5     0.5     0.5   
1  0000247867823ef7    0.5           0.5      0.5     0.5     0.5   
2  00013b17ad220c46    0.5           0.5      0.5     0.5     0.5   
3  00017563c3f7919a    0.5           0.5      0.5     0.5     0.5   
4  00017695ad8997eb    0.5           0.5      0.5     0.5     0.5   

   identity_hate  
0            0.5  
1            0.5  
2            0.5  
3            0.5  
4            0.5

In [24]:
# Define preprocessing function
def preprocess(text):
    stopwords_set = set(stopwords.words('english'))
    return ' '.join(
        token.lower() for token in word_tokenize(text)
        if token.isalpha() and token not in stopwords_set)

train_df['comment_text'] = train_df['comment_text'].apply(preprocess)

X = train_df['comment_text']
y = train_df[['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Vectorize the text data
vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=500)
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

model = MLPClassifier(verbose=1)
model.fit(X_train_vectorized, y_train)

accuracy = model.score(X_test_vectorized, y_test)
print("Accuracy:", accuracy)


Iteration 1, loss = 0.82267616
Iteration 2, loss = 0.46848620
Iteration 3, loss = 0.45649224
Iteration 4, loss = 0.45097849
Iteration 5, loss = 0.44727743
Iteration 6, loss = 0.44397299
Iteration 7, loss = 0.44025442
Iteration 8, loss = 0.43708167
Iteration 9, loss = 0.43317132
Iteration 10, loss = 0.42976628
Iteration 11, loss = 0.42646662
Iteration 12, loss = 0.42289303
Iteration 13, loss = 0.41942660
Iteration 14, loss = 0.41572235
Iteration 15, loss = 0.41264445
Iteration 16, loss = 0.40945089
Iteration 17, loss = 0.40615933
Iteration 18, loss = 0.40287390
Iteration 19, loss = 0.39989265
Iteration 20, loss = 0.39697736
Iteration 21, loss = 0.39379713
Iteration 22, loss = 0.39086739
Iteration 23, loss = 0.38781106
Iteration 24, loss = 0.38500824
Iteration 25, loss = 0.38185234
Iteration 26, loss = 0.37930055
Iteration 27, loss = 0.37630431
Iteration 28, loss = 0.37360911
Iteration 29, loss = 0.37080146
Iteration 30, loss = 0.36783331
Iteration 31, loss = 0.36526417
Iteration 32, los

C:\Users\Harshal Tak\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [25]:
# Make predictions on the test data
predictions = model.predict(X_test_vectorized)

# Display the first few predictions
print("Predictions for the first few examples:")
print(predictions[:5])

# Evaluate the model
accuracy = model.score(X_test_vectorized, y_test)
print("Accuracy:", accuracy)

Predictions for the first few examples:
[[1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Accuracy: 0.8733510888297039
